# Generated by Django 4.2.29 on 2026-03-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_galleryimage_schoolinfo_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolinfo',
            name='address',
            field=models.TextField(default='Barahiya, Near Hanuman Temple'),
        ),
    ]
