# Generated by Django 6.0.3 on 2026-04-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_migrate_to_binary'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolinfo',
            name='director_name',
            field=models.CharField(default='Manoj Kumar', max_length=100),
        ),
    ]
