# Generated by Django 6.0.2 on 2026-07-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_result_grade_alter_result_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='class_section',
        ),
        migrations.AddField(
            model_name='teacher',
            name='class_section',
            field=models.ManyToManyField(blank=True, related_name='class_teachers', to='core.schoolclass'),
        ),
    ]
