# Generated by Django 5.2.15 on 2026-07-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_teacher_class_section_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo_url',
            field=models.URLField(blank=True, help_text='External photo URL (optional, used if no uploaded photo)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='photo_url',
            field=models.URLField(blank=True, help_text='External photo URL (optional, used if no uploaded photo)', max_length=500, null=True),
        ),
    ]
