# Generated by Django 6.0.2 on 2026-08-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_student_photo_url_teacher_photo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_plus_min', models.IntegerField(default=90, help_text='Minimum % for A+ grade')),
                ('a_min', models.IntegerField(default=80, help_text='Minimum % for A grade')),
                ('b_plus_min', models.IntegerField(default=70, help_text='Minimum % for B+ grade')),
                ('b_min', models.IntegerField(default=60, help_text='Minimum % for B grade')),
                ('c_min', models.IntegerField(default=50, help_text='Minimum % for C grade')),
                ('d_min', models.IntegerField(default=40, help_text='Minimum % for D grade')),
                ('pass_percentage', models.IntegerField(default=40, help_text='Minimum % to PASS')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grade Configuration',
                'verbose_name_plural': 'Grade Configuration',
            },
        ),
    ]
