# Generated by Django 6.0.2 on 2026-08-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_gradeconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='raw_password',
            field=models.CharField(blank=True, help_text='Plaintext password set by admin for registration certificate', max_length=128, null=True),
        ),
    ]
