# Generated by Django 5.2.15 on 2026-08-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_adminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Telegram numeric Chat ID for 2FA OTP delivery (get it from @userinfobot)', max_length=50, null=True),
        ),
    ]
