# Generated by Django 5.2.15 on 2026-08-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_telegram_chat_id_to_adminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolinfo',
            name='principal_signature',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='principal_signature_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='principal_signature_mimetype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='principal_signature_url',
            field=models.URLField(blank=True, help_text='External Principal signature URL (optional)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='signature',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='signature_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='signature_mimetype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='signature_url',
            field=models.URLField(blank=True, help_text='External signature URL (optional, used if no uploaded signature)', max_length=500, null=True),
        ),
    ]
