# Generated by Django on 2026-08-25
from django.db import migrations
from django.contrib.auth.hashers import make_password


def seed_permanent_admins(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Admin = apps.get_model('core', 'Admin')
    AdminProfile = apps.get_model('core', 'AdminProfile')

    ADMIN_ACCOUNTS = [
        {
            'username': 'admin',
            'email': 'admin@midpoint.com',
            'password': 'admin123',
            'name': 'Administrator',
            'telegram_chat_id': '5215400355',
        },
        {
            'username': 'Bhanu_admin',
            'email': 'bhanu@midpointschool.online',
            'password': 'admin@123',
            'name': 'Bhanu Kumar Singh',
            'telegram_chat_id': '1949979666',
        },
    ]

    for acc in ADMIN_ACCOUNTS:
        username = acc['username']
        email = acc['email']
        password = acc['password']
        name = acc['name']
        telegram_chat_id = acc['telegram_chat_id']
        hashed_pw = make_password(password)

        # 1. Django User
        user = User.objects.filter(username=username).first()
        if not user:
            user = User.objects.filter(email=email).first()

        if not user:
            user = User(
                username=username,
                email=email,
                password=hashed_pw,
                is_staff=True,
                is_superuser=True,
            )
            user.save()
        else:
            user.username = username
            user.email = email
            user.password = hashed_pw
            user.is_staff = True
            user.is_superuser = True
            user.save()

        # 2. AdminProfile with Telegram Chat ID
        profile, _ = AdminProfile.objects.get_or_create(user_id=user.id)
        profile.telegram_chat_id = telegram_chat_id
        profile.save()

        # 3. Legacy Admin entry
        admin_entry = Admin.objects.filter(email=email).first()
        if not admin_entry:
            admin_entry = Admin(
                email=email,
                name=name,
                role='Administrator',
                phone='',
                password=hashed_pw,
            )
            admin_entry.save()
        else:
            admin_entry.name = name
            admin_entry.password = hashed_pw
            admin_entry.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_schoolinfo_principal_signature_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_permanent_admins, reverse_func),
    ]
