# Generated by Django 6.0.2 on 2026-09-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_seed_permanent_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL (optional, used if no uploaded image)', max_length=500, null=True),
        ),
    ]
