# Generated by Django 6.0.2 on 2026-09-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_galleryimage_add_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolinfo',
            name='home_marquee_text',
            field=models.TextField(blank=True, default='🚀 ADMISSION OPEN NOW FOR NEW SESSION 2026-2027 • REGISTER YOUR INTEREST TODAY • CLICK HERE TO SEND AN INQUIRY 🚀', help_text='Scrolling marquee text shown on the Home page', null=True),
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='result_marquee_text',
            field=models.TextField(blank=True, default='✨ CLICK FOR DOWNLOAD NEW EXAMINATION ADMIT CARD ✨', help_text='Scrolling marquee text shown on the Result page', null=True),
        ),
    ]
